### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by marcus433** [atom/node#5]
It would be great if the atom IO js fork could be updated as in the latest version of IO an issue with TLS has been addressed https://github.com/iojs/io.js/issues/923

**Comment by zcbenz** [comment]
The HEAD of io.js is using a much newer version of V8 that not compatible with Chrome 40, so you have to wait until Chrome 42 becomes stable.

**Comment by dlmanning** [comment]
@zcbenz : The latest release of io.js (1.4.3) uses v8 4.1.0.21. Chrome 41, which went stable today, uses the same v8 version. Should be possible to update dependencies, no? In addition to the issue @marcus433 mentioned, updating io.js would restore compatibility with many native modules due to an updated version of https://github.com/rvagg/nan being included.

**Comment by zcbenz** [comment]
@dlmanning Yeah once we have upgraded to Chrome 41 I'll update io.js to the latest version.

**Comment by dlmanning** [comment]
@zcbenz Rad. Thanks!
